import random
r1 = random.randint(0, 9)
r2 = random.randint(0, 9)
r3 = random.randint(0, 9)
r4 = random.randint(1, 6)
r5 = random.randint(1, 6)
r6 = random.randint(1, 6)
r7 = random.randint(1, 6)
print('Kolminumeroinen numerolukko koodi',r1, r2, r3)
print('Nelinumeroinen numerolukko koodi', r4, r5, r6, r7)
