print("Tervetuloa opiskelemaan Python-kieltä!")
print("Tervetuloa opiskelemaan Python-kieltä!")
print("Tervetuloa opiskelemaan Python-kieltä!")
print("Tervetuloa opiskelemaan Python-kieltä!")
print("Tervetuloa opiskelemaan Python-kieltä!")